name: test

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORK_COUNT: 0
  FAIL_FAST: 1
  SHOW_ERROR_DETAIL: 1
  #multi-version size limit
  VERSIONS_LIMIT: 1
  CANDIDATE_VERSIONS: '
    spring.version:5.3.24;
    spring-boot.version:2.7.6;
    '

jobs:
  print-config:
    runs-on: ubuntu-latest
    steps:
      - name: Print operating system information
        run: |
          echo "OS Information:"
          uname -a

      - name: Print CPU information
        run: |
          echo "CPU Information:"
          lscpu

      - name: Print Memory information
        run: |
          echo "Memory Information:"
          free -h

      - name: Print Disk information
        run: |
          echo "Disk Information:"
          df -h

      - name: Check network information
        run: |
          echo "Network Information:"
          ifconfig -a || ip addr

      - name: Print environment variables
        run: |
          echo "Environment Variables:"
          env
  build-source:
    name: "Build Dubbo"
    runs-on: ubuntu-latest
    steps:
      - name: "Build Dubbo with Maven333"
        run: |
          #!/bin/bash
          runtime_para_pairs="dubbo.protocol.name|dubbo|dubbo.protocol.serialization|hessian2@dubbo.protocol.name|dubbo|dubbo.protocol.serialization|fastjson2"
          IFS='|' read -ra prop_array <<< "$runtime_para_pairs"
          for ((i=0; i<${#prop_array[@]}; i+=2)); do
            echo "${prop_array[i]}=${prop_array[i+1]}"
          done
