name: test

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORK_COUNT: 0
  FAIL_FAST: 1
  SHOW_ERROR_DETAIL: 1
  #multi-version size limit
  VERSIONS_LIMIT: 1
  CANDIDATE_VERSIONS: '
    spring.version:5.3.24;
    spring-boot.version:2.7.6;
    '

jobs:
  check-benchmark-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'wxbty/dubbo-samples'
          ref: bh-test
      - name: Check if directory exists
        run: |
          #!/bin/bash
          cd test
          PATH_TO_CHECK="../10-task/dubbo-samples-benchmark/"
          if [ ! -d "$PATH_TO_CHECK" ]; then
            exit 1
          fi

  build-source:
    name: "Build Dubbo"
    needs: check-benchmark-path
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.dubbo-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: dubbo
      - name: "Dubbo cache"
        id: dubbocache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/org/apache/dubbo
          key: ${{ runner.os }}-dubbo-snapshot-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-dubbo-snapshot-${{ github.sha }}
      - name: "Build Dubbo with Maven"
        if: steps.dubbo-cache.outputs.cache-hit != 'true'
        run: |
          #!/bin/bash
          cd test
          echo "hit"
      - name: "Build Dubbo with Maven"
        if: steps.dubbo-cache.outputs.cache-hit != 'false'
        run: |
          #!/bin/bash
          cd test
          echo "not hit"
